services:
  - type: web
    name: roleroom
    env: node
    plan: free
    buildCommand: npm install && cd client && npm install --include=dev && ./node_modules/.bin/vite build
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 22.5.0
